"""empty message

Revision ID: 3b38504d2100
Revises: None
Create Date: 2014-10-09 10:50:14.502147

"""

# revision identifiers, used by Alembic.
revision = '3b38504d2100'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
