"""empty message

Revision ID: a34d26cc1a1
Revises: 2d90dacaa842
Create Date: 2014-10-14 19:40:20.001080

"""

# revision identifiers, used by Alembic.
revision = 'a34d26cc1a1'
down_revision = '2d90dacaa842'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['expression_id'], ['expression.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
   ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    ### end Alembic commands ###
